name: Slack Notifications

on:
  push:
    branches:
      - master # Replace with your branch name

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Send Slack Notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        MESSAGE="New commit pushed to the repository by $GITHUB_ACTOR. Commit message: $GITHUB_SHA"
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
