name: Slack Notifications

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v39
      with:
        separator: "\n"

    - name: Send Slack Notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        AUTHOR="$GITHUB_ACTOR"
        AUTHOR_PROFILE="https://github.com/$AUTHOR"
        AUTHOR_IMAGE="https://github.com/$AUTHOR.png"
        REPO_NAME="$GITHUB_REPOSITORY"
        EVENT_NAME="New Commit"
        COMMIT_ID="$GITHUB_SHA"
        COMMIT_MESSAGE="$(git log --format=%B -n 1 $GITHUB_SHA)"
        COMMIT_LINK="https://github.com/$REPO_NAME/commit/$GITHUB_SHA"
        MODIFIED_FILES="${{ steps.changed-files.outputs.all_modified_files }}"
        DELETED_FILES="${{ steps.changed-files.outputs.deleted_files }}"
        
        # Identify deleted files by comparing lists
        MODIFIED_FILES_LIST=""
        for FILE in $MODIFIED_FILES; do
          if [[ " ${DELETED_FILES} " =~ " $FILE " ]]; then
            MODIFIED_FILES_LIST="$MODIFIED_FILES_LIST\n- ($FILE) (deleted)"
          else
            MODIFIED_FILES_LIST="$MODIFIED_FILES_LIST\n- $FILE"
          fi
        done

        PAYLOAD="{
          \"attachments\": [
            {
              \"color\": \"#36a64f\",
              \"title\": \"$REPO_NAME\",
              \"title_link\": \"https://github.com/$REPO_NAME\",
              \"text\": \"$EVENT_NAME: <$COMMIT_LINK|$COMMIT_MESSAGE>\nModified Files:$MODIFIED_FILES_LIST\",
              \"footer_icon\": \"$AUTHOR_IMAGE\",
              \"footer\": \"<${AUTHOR_PROFILE}|$AUTHOR>\"
            }
          ]
        }"

        curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
