name: Slack Notifications

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Send Slack Notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        AUTHOR="$GITHUB_ACTOR"
        AUTHOR_PROFILE="https://github.com/$AUTHOR"
        AUTHOR_IMAGE="https://github.com/$AUTHOR.png"
        REPO_NAME="$GITHUB_REPOSITORY"
        EVENT_NAME="New Commit"
        COMMIT_ID="$GITHUB_SHA"
        COMMIT_MESSAGE="$(git log --format=%B -n 1 $GITHUB_SHA)"
        COMMIT_LINK="https://github.com/$REPO_NAME/commit/$GITHUB_SHA"
        CHANGED_FILES=$(git diff --name-only $GITHUB_SHA)
        FILE_LIST=""

        for FILE in $CHANGED_FILES; do
          FILE_LIST="$FILE_LIST\n- $FILE"
        done

        PAYLOAD="{
          \"attachments\": [
            {
              \"color\": \"#36a64f\",
              \"title\": \"$REPO_NAME\",
              \"title_link\": \"https://github.com/$REPO_NAME\",
              \"text\": \"$EVENT_NAME: <$COMMIT_LINK|$COMMIT_MESSAGE>\nChanged Files:\n$FILE_LIST\",
              \"footer_icon\": \"$AUTHOR_IMAGE\",
              \"footer\": \"<${AUTHOR_PROFILE}|$AUTHOR>\"
            }
          ]
        }"

        curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
