name: Slack Notifications

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v39

    - name: List all added files
      run: |
        for file in ${{ steps.changed-files.outputs.added_files }}; do
          echo "$file was added"
        done
        
    - name: List all added files
      run: |
        for file in ${{ steps.changed-files.outputs.modified_files }}; do
          echo "$file was modifies"
        done
      
    - name: Send Slack Notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        AUTHOR="$GITHUB_ACTOR"
        AUTHOR_PROFILE="https://github.com/$AUTHOR"
        AUTHOR_IMAGE="https://github.com/$AUTHOR.png"
        REPO_NAME="$GITHUB_REPOSITORY"
        EVENT_NAME="New Commit"
        COMMIT_ID="$GITHUB_SHA"
        COMMIT_MESSAGE="$(git log --format=%B -n 1 $GITHUB_SHA)"
        COMMIT_LINK="https://github.com/$REPO_NAME/commit/$GITHUB_SHA"

        PAYLOAD="{
          \"attachments\": [
            {
              \"color\": \"#36a64f\",
              \"title\": \"$REPO_NAME\",
              \"title_link\": \"https://github.com/$REPO_NAME\",
              \"text\": \"$EVENT_NAME: <$COMMIT_LINK|$COMMIT_MESSAGE>\nChanged Files:\n$FILE_LIST\",
              \"footer_icon\": \"$AUTHOR_IMAGE\",
              \"footer\": \"<${AUTHOR_PROFILE}|$AUTHOR>\"
            }
          ]
        }"

        curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
