name: Slack Notifications

on:
  push:
    branches:
      - master # Replace with your branch name

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Send Slack Notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        AUTHOR="$GITHUB_ACTOR"
        COMMIT_MESSAGE="$(git log --format=%B -n 1 $GITHUB_SHA)"
        COMMIT_LINK="https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
        PAYLOAD="{
          \"attachments\": [
            {
              \"color\": \"#36a64f\",
              \"title\": \"New Commit Notification\",
              \"fields\": [
                {
                  \"title\": \"Author\",
                  \"value\": \"$AUTHOR\",
                  \"short\": true
                },
                {
                  \"title\": \"Commit Message\",
                  \"value\": \"$COMMIT_MESSAGE\",
                  \"short\": false
                }
              ],
              \"footer\": \"<${COMMIT_LINK}|View Commit>\"
            }
          ]
        }"
        curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
